#!/bin/bash
#SBATCH -N 4
#SBATCH -C haswell
#SBATCH -q debug
#SBATCH -J qpic
#SBATCH --mail-user=zhaoyujian@ucla.edu
#SBATCH --mail-type=ALL
#SBATCH -t 00:29:00

#OpenMP settings:
export OMP_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread


#run the application:
srun -n 128 -c 2 python3 sp_pusher.py 
# srun -n 512 -c 2 --cpu_bind=cores ~/QPAD_noacc/bin/qpad.e
# srun -n 16 -c 2 --cpu_bind=cores ~/quickpic-dev/source/qpic.e

# salloc -N 1 -C haswell -q interactive -t 01:00:00
